name: Terraform

on: 
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Terraform
      run: |
        wget https://releases.hashicorp.com/terraform/0.15.4/terraform_0.15.4_linux_amd64.zip
        unzip terraform_0.15.4_linux_amd64.zip
        mv terraform /usr/local/bin/
    - name: Terraform init
      run: terraform init

    - name: Terraform plan
      run: terraform plan -out=tfplan

    - name: Terraform apply and sleep
      run: |
        terraform apply -auto-approve tfplan
        sleep 200
